---
DEBUG: true
WEB_SERVER_PORT: 8001
dbConfig:
  DB_NAME: yeu-ai
  DB_HOST: mongodb://127.0.0.1:27017
  DB_USERNAME:
  DB_PASSWORD:
modelConfig:
  MODELS_DIR: model_files
  INTENT_MODEL_NAME: intent.model
  TRAIN_DATA_NAME: intent.txt
  DEFAULT_FALLBACK_INTENT_NAME: fallback
  DEFAULT_WELCOME_INTENT_NAME: init_conversation
